CC ?= gcc
all:
	$(CC) -g -O0 malloc_no_free_array_out_of_bound.c -o malloc_no_free_array_out_of_bound.exe
	$(CC) -g -O0 memory_no_init.c -o memory_no_init.exe
	$(CC) -g -O0 memory_rw_out_of_bound.c -o memory_rw_out_of_bound.exe
	$(CC) -g -O0 memory_copy_overlap.c -o memory_copy_overlap.exe
	$(CC) -g -O0 malloc_free_not_pair.c -o malloc_free_not_pair.exe
	$(CC) -g -O0 memory_leak.c -o memory_leak.exe
	